# Generated by Django 6.0.4 on 2026-05-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_roadmap_modulo_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='opcoes',
            field=models.JSONField(blank=True, help_text='Lista de opções de múltipla escolha', null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='pergunta',
            field=models.TextField(blank=True, help_text='Pergunta para validação da tarefa', null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='resposta_correta',
            field=models.CharField(blank=True, help_text='O texto exato da opção correta', max_length=255, null=True),
        ),
    ]
