# Generated by Django 6.0.4 on 2026-05-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tarefa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_agendada',
            field=models.DateField(blank=True, help_text='Data agendada para realizar a tarefa', null=True),
        ),
    ]
